name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: [windows-latest, ubuntu-18.04]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       

      - name: Super-Linter
        uses: super-linter/super-linter@v5.0.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
